Remove reinterpret_cast from code.

diff --git a/src/test_reinterpret_cast b/src/test_reinterpret_cast
--- a/src/test_reinterpret_cast
+++ b/src/test_reinterpret_cast
@@ -1,15 +1,10 @@
 #!/bin/sh
 
-do_static_check() {
-find . -type f -name "$2" |
-while read filename; do
-grep -H "$1" "$filename" && exit 1
-done
+files=$(find . -type f -name "*.cc" -or -name "*.hh")
+
+check() {
+echo "Checking for $1... "
+grep -H "$1" $files && echo "$1: FAIL" || echo "$1: OK"
 }
 
-static_check() {
-do_static_check "$1" "*.cc"
-do_static_check "$1" "*.hh"
-}
-
-static_check reinterpret_cast
+check reinterpret_cast
